sudo: false # make sure we run in the container infrastructure, which is faster
language: python
python:
- '2.7'
cache:
  directories:
    - $HOME/.cache/pip
before_install:
- openssl aes-256-cbc -K $encrypted_389dd021eb6c_key -iv $encrypted_389dd021eb6c_iv
  -in fabfile/cfa-chime-keypair.id_rsa.enc -out fabfile/cfa-chime-keypair.id_rsa -d
- chmod 400 fabfile/cfa-chime-keypair.id_rsa
install:
- git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
- eval "$(rbenv init -)"
- export PATH="$HOME/.rbenv/bin:$PATH"
- ./jekyll/install-jekyll.sh
- pip install -r requirements.txt
- pip install -r fabfile/requirements.txt
script:
- "$SUITE"
notifications:
  webhooks:
    - http://project-monitor.codeforamerica.org/projects/1bf2f3b3-bed8-42bc-91e8-d47f873443de/status
    - http://chime-admin.chimecms.org/ops/travis
    - http://demo-admin.chimecms.org/ops/travis
    - http://springfield-admin.chimecms.org/ops/travis
  slack:
    secure: jayLiI1FjF5/M4WtL5mjO+2NOnCJZI+7IhMvZPSUiikutZSrxCvggf2C/YtlAD2NaxZXrCpnVgdB4XjQTnmRdo8U/M7pLbAF2JVgphSizrRhEY15tIPuyRRKqCQMZo5fz3+Tb6wvgLEGHxVhJv8COfe9zuwlVTcK9XmXrJkPYBE=
# AWS_ACCESS_KEY AWS_SECRET_KEY SSH_PRIVATE_KEY_PATH TESTING_EMAIL TESTING_PASSWORD
env:
  matrix:
    - SUITE='nosetests test/unit'
####- SUITE='env BROWSERS_TO_TEST=supported TEST_RETRY_COUNT=3 fab test_chime:despawn_on_failure=t'
  global:
    - secure: M+PrGzEfHRj+mPn7d1vHC0n/IQN6fNGER2dhG8qBE8wfC3tfaB3F50R8YSR9R5SdkdapxtgEjPgGvR3agum999qYXo839nra0zq2l3DeQYvwM0IXX0JlscwUkBrMtqMFW9iIIyxB6dgdksUJ5Zz7qcYudm+Msr15iob3DfIxZqs=
    - secure: C8Br1052Hqd+X2OS6g+x31gZtwIzWSq1M2fvGxgIWR+wqZ5IQ6NfkTD2Ht6KwtW4fMUo/41le3t+AFReQeSMZ16l7yvkC7BWcrqQOWaNXNm9Gj1t1QFMuKQvhv3NT0H6HGLXXGMrHwLKDHTCAnSOe8k/xbhqG8Og4UF0hoOF7lY=
    - secure: dVA5sQPJ2jE7wSENMEgqLuoyvFae2ghxBHPru52XOKSRtSgqXoqgf/jbKbpEwCDxCqlIFpdIEv33RtmmNvBMxYhmP5uToOBcyOzyc5/HbMn/+53nclLN6yTWGPtH3JT+5kqds/YL/HWdP3DWuel5gBn175SzTSFuszRPAbCyrMs=
    - secure: I/6KqYx2i0xwCtfOW3VIORP0bMjYuD9gHpdQx1iVeKYYoVTHMnUP2RQbmu8uA31VPSZlKBofod7FX1VO41FR8M+NI4r+IrImOq/J9aWC9Upq+dBB1rPnEPfJFxPmGg+sVoNCK2utZXE1z/8WkopYAeZ9wdE4DM6235a12dIyxIY=
    - secure: fW/O/iFDOwI/sINW2vYCDf+H4QahaaI0YNpEcJ7QXl0Nzm4UcCWLu39gYSCeaIwjfUwPFvQ/e09HH8ba2FtsdeeX+8pPECE4Ilqj0m4sZOItbSfYTdfU25okgmcsy9T652CNhUfqnkbire1Fq5nwL31CKc4BDKP0iQqSd9m3d2k=
deploy:
  provider: script
  script: ./deploy-to-docker.sh ${DOCKER_TRIGGER_TOKEN}
  on:
    branch: master
