language: python
python:
  - "2.7"
before_install: 
  - sudo apt-get update -y
  - sudo apt-get install git
  - sudo apt-get install apache2
install: pip install -r requirements.txt
script:  python test/test.py
notifications:
  webhooks: http://project-monitor.codeforamerica.org/projects/1bf2f3b3-bed8-42bc-91e8-d47f873443de/status
  slack:
    secure: Xjg6TC3rHw8jX+ODmS32FOXKX95IgjgViQSC7E7VL3ZF+3C8IBVCipX70MRVfUb3pVa

